apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  labels:
    name: app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: <Host>
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: appback-service
            port: 
              number: 80
